Procedimento imprimindoNaTela(nome: caractere; idade : inteiro)


inicio
escreval
escreval("Nome digitado: ",nome)
escreval("Idade digitada: ",idade)

fimprocedimento


Algoritmo "primeiro_projeto"

Var
// Seção de Declarações das variáveis 
nome: caractere
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual seu nome: ")
leia(nome)

escreva("Qual a sua idade: ")
leia(idade)

imprimindoNaTela(nome,idade)

Fimalgoritmo